# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-03-25 13:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=50, verbose_name='物料名称')),
                ('itemsize', models.CharField(max_length=50, verbose_name='规格型号')),
                ('count', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='库存数量')),
                ('producer', models.CharField(max_length=50, verbose_name='生产厂家')),
                ('supplier', models.CharField(max_length=50, verbose_name='供应商')),
                ('price', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='单价')),
                ('location', models.CharField(blank=True, max_length=50, null=True, verbose_name='库位号')),
                ('maxcnt', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='最高库存')),
                ('mincnt', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='最低库存')),
                ('classify', models.CharField(choices=[('0', '工具'), ('1', '辅料'), ('2', '备件')], max_length=20, verbose_name='分类')),
                ('remark', models.CharField(blank=True, max_length=200, verbose_name='备注')),
            ],
            options={
                'verbose_name': 'item',
                'verbose_name_plural': 'item',
            },
        ),
        migrations.CreateModel(
            name='ItemReturn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=20, null=True, verbose_name='code')),
                ('operator', models.CharField(max_length=40)),
                ('execute_time', models.DateTimeField(blank=True, null=True, verbose_name='execute time')),
                ('amount', models.IntegerField(null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Item', verbose_name='item')),
            ],
            options={
                'verbose_name': 'ware return',
                'verbose_name_plural': 'ware return',
            },
        ),
        migrations.CreateModel(
            name='StockIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=20, null=True, verbose_name='code')),
                ('operator', models.CharField(max_length=40)),
                ('execute_time', models.DateTimeField(blank=True, null=True, verbose_name='execute time')),
                ('amount', models.IntegerField(null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Item', verbose_name='item')),
            ],
            options={
                'verbose_name': 'StockIn',
                'verbose_name_plural': 'StockIn',
            },
        ),
        migrations.CreateModel(
            name='StockOut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=20, null=True, verbose_name='code')),
                ('operator', models.CharField(max_length=40)),
                ('execute_time', models.DateTimeField(blank=True, null=True, verbose_name='execute time')),
                ('amount', models.IntegerField(null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Item', verbose_name='item')),
            ],
            options={
                'verbose_name': 'StockOut',
                'verbose_name_plural': 'StockOut',
            },
        ),
    ]
